const musics = "Music",
    dances = "Dance",
    theatres = "Theatre",
    painters = "Painter",
    designers = "Designer",
    writers = "Writer",
    photographys = "Photography",
    tattoos = "Tattoo",
    graffittis = "Graffiti";
